#spring.application.name=supportportal
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/supportportal_schema
#spring.datasource.username=root
#spring.datasource.password=root
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
server:
  port: 8081

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/supportportal_schema
      password: root
      username: root
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: create
#    mvc:
#      throw-exception-if-no-handler-found: true
#    resources:
#      add-mapping: false